CREATE TABLE IF NOT EXISTS properties (
  id TEXT PRIMARY KEY,
  wilaya TEXT NOT NULL,
  moughataa TEXT NOT NULL,
  neighborhood TEXT NOT NULL,
  house_number TEXT NOT NULL,
  rooms_count INTEGER NOT NULL DEFAULT 1,
  type TEXT NOT NULL DEFAULT 'منزل أرضي',
  accessories TEXT DEFAULT '',
  owner_name TEXT NOT NULL,
  owner_phone TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  tenant_name TEXT NOT NULL,
  tenant_phone TEXT NOT NULL,
  tenant_id TEXT NOT NULL,
  contract_date DATE NOT NULL,
  contract_type TEXT NOT NULL DEFAULT 'بعقد',
  monthly_rent NUMERIC NOT NULL DEFAULT 0,
  payment_system TEXT NOT NULL DEFAULT 'مقدم',
  arrears NUMERIC NOT NULL DEFAULT 0,
  snde_status BOOLEAN NOT NULL DEFAULT true,
  somelec_status BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
